version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10.

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: dev-site-v1.1.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Jekyll build
          command: bundle exec jekyll serve
