version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0
  ruby: circleci/ruby@1.1.0

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/push-docker-image:
          requires:
            - build
          filters:
            branches:
              only: dev-site-v1.1.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
